USE [TimeTable]
GO

/****** Object:  Index [IX_Chair_Code]    Script Date: 14.03.2017 21:26:22 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Chair_Code] ON [dbo].[Chair]
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

