USE [master]
GO

/****** Object:  Database [TimeTable]    Script Date: 14.03.2017 21:18:57 ******/
CREATE DATABASE [TimeTable]
 CONTAINMENT = PARTIAL
 ON  PRIMARY 
( NAME = N'TimeTable', FILENAME = N'C:\DataBase\MSSQL12.SQLSERVERIT1\MSSQL\DATA\TimeTable.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TimeTable_log', FILENAME = N'C:\DataBase\MSSQL12.SQLSERVERIT1\MSSQL\DATA\TimeTable_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TimeTable] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeTable].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeTable] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeTable] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeTable] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeTable] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeTable] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeTable] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimeTable] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeTable] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeTable] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeTable] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeTable] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeTable] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeTable] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeTable] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeTable] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimeTable] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeTable] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeTable] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeTable] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeTable] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeTable] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeTable] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeTable] SET RECOVERY FULL 
GO

ALTER DATABASE [TimeTable] SET  MULTI_USER 
GO

ALTER DATABASE [TimeTable] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeTable] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeTable] SET DEFAULT_FULLTEXT_LANGUAGE = 1049 
GO

ALTER DATABASE [TimeTable] SET DEFAULT_LANGUAGE = 1049 
GO

ALTER DATABASE [TimeTable] SET NESTED_TRIGGERS = ON 
GO

ALTER DATABASE [TimeTable] SET TRANSFORM_NOISE_WORDS = OFF 
GO

ALTER DATABASE [TimeTable] SET TWO_DIGIT_YEAR_CUTOFF = 2049 
GO

ALTER DATABASE [TimeTable] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeTable] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TimeTable] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeTable] SET  READ_WRITE 
GO

