//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{

    public partial class ChairToSpecialization
    {
        public long Id { get; set; }
        public long ChairId { get; set; }
        public long SpecializationId { get; set; }
        public bool Active { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModify { get; set; }
        public string UserModify { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
