//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomToClassroomProperty
    {
        public long Id { get; set; }
        public long ClassroomId { get; set; }
        public long ClassroomPropertyId { get; set; }
        public bool Active { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModify { get; set; }
        public string UserModify { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual ClassroomProperty ClassroomProperty { get; set; }
    }
}
